const fs=require('fs'),vm=require('vm'),assert=require('assert');
const path=require('path'); const base=path.resolve(__dirname,'..')+'/'; const qaDir=require('os').tmpdir()+'/calabozos-python-qa/';fs.mkdirSync(qaDir,{recursive:true});
const html=fs.readFileSync(base+'juego.html','utf8');
assert(html.includes('attr==="data-font"?"data-font-size":attr'),'font-size accessibility mapping');assert(html.includes('data-motion="on"'),'reduced-motion CSS');
assert(html.includes('class="mission-consigna" id="zBrief"'),'brief inside mission card');
assert(html.includes('assets/pip-states-v3.png'),'Pip multi-state sprite asset');
assert(html.includes('pip-state-thinking')&&html.includes('pip-state-warning'),'Pip contextual visual states');
assert(html.includes("center('20'"),'d20 replaces generic PY seal');
assert(html.includes('CALABOZOS_HEROES_JPEG')&&!html.includes("center('CC BY'"),'class portrait replaces CC license badge');
assert(html.includes('assets/hero-sprites/')&&html.includes('function heroStageForProgress'),'evolving class sprites in hero card');
assert(html.includes('hero-sprite-loop')&&html.includes('hero-sprite-action')&&html.includes('hero-sprite-evolve'),'hero uses frame-by-frame idle, action and evolution');
assert(html.includes('<button class="pj-av')&&!/\.inventario \.pj-av:before\{[^}]*dashed/.test(html),'round interactive portrait without rotating dotted ring');
assert(html.includes('id="evoTrack"')&&html.includes('on("pjAv","click"'),'visible and interactive evolution track');
assert(html.includes('EVIDENCIA FORMATIVA')&&html.includes('function masteryTotals'),'formative mastery without XP punishment');
assert(html.includes('reward-particle'),'achievement reward animation');
const manual=fs.readFileSync(base+'manual-jugador.html','utf8');assert(manual.includes('Todo lo que necesitás para avanzar por cualquier universo del código.'),'player manual introduction');
assert(manual.includes('manual-campaign.js')&&manual.includes('Glosario completo de Python'),'complete manual and glossary');
assert(fs.readFileSync(base+'assets/manual-campaign.js','utf8').includes('dragon-1'),'manual includes final level');
assert(!fs.existsSync(base+'informe-docente.html'),'teacher report removed from final interface');
assert(fs.existsSync(base+'assets/journey.js')&&fs.existsSync(base+'assets/journey.css'),'hero journey assets');
assert(fs.existsSync(base+'assets/responsive.css'),'responsive asset');
const responsive=fs.readFileSync(base+'assets/responsive.css','utf8');
assert(responsive.includes('@media (max-width:760px)')&&responsive.includes('min-height:44px')&&responsive.includes('html.pip-only .pip-chat'),'mobile, touch and pip-only responsive rules');
assert(responsive.includes('@media (min-width:1000px) and (max-height:800px)'),'1366x768 landscape desktop layout');
assert(fs.readFileSync(base+'assets/accessibility.js','utf8').includes('@media(max-width:520px){#cpA11yFab'),'shared accessibility panel adapts to phones');
['juego.html','index.html','guia-docente.html','manual-jugador.html','ejemplo-input.html','ejemplo-print.html'].forEach(function(file){assert(fs.readFileSync(base+file,'utf8').includes('assets/responsive.css'),file+' loads responsive CSS')});
['niveles/ejemplo-input.html','niveles/ejemplo-print.html'].forEach(function(file){assert(fs.readFileSync(base+file,'utf8').includes('../assets/responsive.css'),file+' loads responsive CSS')});
assert(html.includes('id="heroJourney"')&&html.includes('journey-landmark final'),'footer journey and final dragon milestone');
const journey=fs.readFileSync(base+'assets/journey.js','utf8');assert(journey.includes("data.name+'|'+data.clase+'|'+data.scope")&&journey.includes('done>previous.done')&&journey.includes('prefers-reduced-motion'),'journey advances from completion and respects reduced motion');
assert(fs.readFileSync(base+'sw.js','utf8').includes('assets/journey.js')&&fs.readFileSync(base+'sw.js','utf8').includes('assets/responsive.css'),'offline journey and responsive cache');
const campaignsSrc=fs.readFileSync(base+'assets/campaigns.js','utf8');new vm.Script(campaignsSrc,{filename:'campaigns.js'});
const campaignContext={window:{}};vm.createContext(campaignContext);vm.runInContext(campaignsSrc,campaignContext);
assert(campaignContext.window.CP_CAMPAIGNS.calabozos&&campaignContext.window.CP_CAMPAIGNS.jujutsu&&campaignContext.window.CP_CAMPAIGNS.multiverso,'three campaign configurations');
assert(campaignContext.window.CP_CAMPAIGNS.jujutsu.topicOverrides.condicionales.title.includes('VELO'),'Jujutsu curricular narrative override');
assert(html.includes('function parseCampaignFromURL')&&html.includes('q.get(\"campana\")')&&html.includes('raw=qp(\"tema\")'),'campaign and curricular URL filters coexist');
assert(html.includes('data-campaign=\"jujutsu\"')&&!html.includes('<select id=\"pipHelpLevel\"'),'campaign selector and no visible Pip help selector');
assert(html.includes('pipPrefs:{helpLevel:\"strong\"}'),'strong Pip guidance by default');
const indexHtml=fs.readFileSync(base+'index.html','utf8');assert(indexHtml.includes('calabozos/index.html')&&indexHtml.includes('jujutsu/index.html')&&indexHtml.includes('multiverso/index.html'),'landing page exposes three campaign folders');
const swText=fs.readFileSync(base+'sw.js','utf8');assert(swText.includes('assets/campaigns.js')&&swText.includes('assets/campaigns.css'),'campaign assets cached offline');
    for(const cid of ['calabozos','jujutsu','multiverso']){assert(fs.existsSync(base+cid+'/index.html')&&fs.existsSync(base+cid+'/juego.html'),cid+' campaign folder');const loader=fs.readFileSync(base+cid+'/juego.html','utf8');assert(loader.includes("fetch('../juego.html'")&&loader.includes("searchParams.set('campana'"),cid+' uses shared canonical engine');}
    assert(swText.includes('./calabozos/juego.html')&&swText.includes('./jujutsu/juego.html')&&swText.includes('./multiverso/juego.html'),'campaign folder entry points cached offline');

assert(!html.includes('id="btnSaveFile"')&&!html.includes('id="btnLoadFile"'),'manual save/import buttons removed');
assert(html.includes('function exportSaveFile(')&&html.includes('function importSaveFile('),'backup routines preserved');
assert(!html.includes('btnTeacherReport')&&!html.includes('btnStudentPDF')&&!html.includes('informe-docente.html'),'teacher report and duplicate inventory controls removed');
assert(html.includes('id="pipCapability"')&&html.includes('showPipCapability')&&html.includes('5200'),'temporary Pip capability notice');
assert(/pip-sugs\{display:grid;grid-template-columns:repeat\(2/.test(fs.readFileSync(base+'assets/v16.css','utf8')),'separated Pip quick actions');
const journeyEls={heroJourney:{hidden:true,setAttribute(){}},journeyActor:{className:'',style:{}},journeySprite:{style:{}},journeySteps:{innerHTML:'',appendChild(){}},journeyFill:{style:{}},journeyCount:{},journeyNext:{},journeyName:{},journeyStatus:{}};
const journeyContext={window:{matchMedia:()=>({matches:false})},document:{documentElement:{getAttribute:()=>"off"},getElementById:id=>journeyEls[id],createElement:()=>({style:{}})},setTimeout:()=>1,clearTimeout(){}};journeyContext.window.window=journeyContext.window;vm.createContext(journeyContext);vm.runInContext(journey,journeyContext);
const routeMissions=[{id:'a',title:'A'},{id:'b',title:'B'}],routeData={active:true,pipOnly:false,name:'Luna',clase:'Mago',scope:'campaign',missions:routeMissions,completed:{},sprite:'mago.png'};
journeyContext.window.CalabozosJourney.update(routeData);const routeStart=journeyEls.journeyActor.style.left;routeData.completed.a=true;journeyContext.window.CalabozosJourney.update(routeData);assert.notEqual(journeyEls.journeyActor.style.left,routeStart);assert(journeyEls.journeyActor.className.includes('advancing'),'journey walks after mission completion');journeyContext.window.CalabozosJourney.update(routeData);assert(journeyEls.journeyActor.className.includes('advancing'),'duplicate refresh does not cancel journey animation');
assert(fs.existsSync(base+'sw.js')&&fs.existsSync(base+'assets/vendor/skulpt/skulpt.min.js')&&fs.existsSync(base+'assets/vendor/codemirror/codemirror.min.js'),'local runtime and offline cache');
assert(html.includes('html.embed-mode #btnHome{display:none!important}'),'home hidden in embedded topics');
assert(html.includes('html.pip-only .pip-chat')&&html.includes('bottom:auto !important'),'Pip iframe geometry reset');
for(const f of fs.readdirSync(base).filter(x=>x.endsWith('.html'))){let h=fs.readFileSync(base+f,'utf8');for(const m of h.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(m[1],{filename:f});}
for(const f of ['index.html','juego.html','manual-jugador.html','guia-docente.html','ejemplo-input.html','ejemplo-print.html'])assert(fs.readFileSync(base+f,'utf8').includes('assets/accessibility.js'),f+' global accessibility');
for(const f of ['niveles/ejemplo-input.html','niveles/ejemplo-print.html'])assert(fs.readFileSync(base+f,'utf8').includes('../assets/accessibility.js'),f+' global accessibility');
const sharedA11y=fs.readFileSync(base+'assets/accessibility.js','utf8');new vm.Script(sharedA11y,{filename:'accessibility.js'});assert(sharedA11y.includes('calabozos-python-preferencias-v1'),'shared accessibility persistence');
let script=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].pop()[1];
script=script.slice(0,script.indexOf('try{bindUI();}'))+`\nwindow.qa={pipRespond:pipRespond,exportPDF:exportPDF,state:state,topics:TOPICS,all:getAll,scope:scopedChallenges,setScope:function(t){temaFiltro=t;modoTema=!!t},setSay:function(f){pipSay=f},setCurrent:function(id){currentId=id},setEditorCode:function(c){getCode=function(){return c}},genSeal:genSeal,parseSeal:parseSeal,applySeal:applySeal,simulate:trySimplePySim,badNames:hasBadPyNames,heroStage:heroStage,heroStageForProgress:heroStageForProgress,heroImagePath:heroImagePath,heroSpritePath:heroSpritePath,recordXpPenalty:recordXpPenalty,xpLostTotal:xpLostTotal,xpTotal:xpTotal,dominio:dominio,minorEvolution:minorEvolution,masteryTotals:masteryTotals,parseCampaign:parseCampaignFromURL,parseTema:parseTemaFromURL};})();`;
const context={window:{},location:{search:'',href:'http://local/juego.html'},document:{querySelector:()=>null,querySelectorAll:()=>[],documentElement:{style:{},classList:{add(){},remove(){}},setAttribute(){}}},console,setTimeout,clearTimeout,setInterval:()=>0,Blob,atob};context.window=context;vm.createContext(context);
vm.runInContext(campaignsSrc,context);vm.runInContext(fs.readFileSync(base+'assets/logo-pdf-data.js','utf8'),context);vm.runInContext(fs.readFileSync(base+'assets/heroes-pdf-data.js','utf8'),context);vm.runInContext(fs.readFileSync(base+'assets/qr-pdf-data.js','utf8'),context);vm.runInContext(fs.readFileSync(base+'assets/ficha-pdf.js','utf8'),context);vm.runInContext(script,context);
const q=context.qa;
context.location.search='?campana=calabozos';assert.equal(q.parseCampaign(),'calabozos');
context.location.search='?campana=jujutsu';assert.equal(q.parseCampaign(),'jujutsu');
context.location.search='?campana=jujutsu&tema=condicionales';assert.equal(q.parseCampaign(),'jujutsu');assert.equal(q.parseTema(),'condicionales');
    context.location.search='?campana=multiverso&tema=bucles';assert.equal(q.parseCampaign(),'multiverso');assert.equal(q.parseTema(),'bucles');
context.location.search='';
let said=[];q.setSay((s,bot)=>{if(bot)said.push(s)});
assert.equal(q.heroStageForProgress(0,39).key,'inicial');assert.equal(q.heroStageForProgress(13,39).key,'veterano');assert.equal(q.heroStageForProgress(26,39).key,'legendario');
assert(q.heroSpritePath('Arquero','legendario').includes('hero-sprites/arquero-legendario.png'),'class/stage sprite selection');
for(const cls of ['mago','guerrero','arquero','explorador'])for(const stage of ['inicial','veterano','legendario'])assert(fs.existsSync(base+'assets/hero-sprites/'+cls+'-'+stage+'.png'),cls+' '+stage+' sprite');
const cases=[['qué es una variable','nombre'],['otro ejemplo','monedas'],['no entendí','etiqueta'],['diferencia entre for y while','iterable'],['diferencia entre print y return','devuelve'],['qué es input','texto'],['ValueError','valor'],['IndexError','posición'],['hola','Pip'],['qué es random','random'],['qué es break','bucle'],['qué es not','invierte'],['qué es una variabel','nombre'],['qué es range','excluye'],['quién sos','Pip'],['cómo lo pruebo','tres casos']];
for(const [ask,expected] of cases){said=[];q.pipRespond(ask);assert(said.join('\n').includes(expected),ask+': '+said);}
q.setEditorCode('nombre = "Luna"\nprint(nombre)');said=[];q.pipRespond('explicá mi código línea por línea');assert(said.join('\n').includes('L1: asigna')&&said.join('\n').includes('L2: muestra'),'Pip line-by-line: '+said);
q.setCurrent('var-3');said=[];q.pipRespond('no entiendo la consigna');assert(said.join('\n').includes('Ordená las instrucciones')&&said.join('\n').includes('Pasos'),'Pip mission summary: '+said);
said=[];q.pipRespond('¿por dónde empiezo?');assert(said.join('\n').includes('asignar antes de usar'),'Pip first step: '+said);
said=[];q.pipRespond('guiame paso a paso');assert(said.join('\n').includes('Paso actual'),'Pip guided tutoring: '+said);
said=[];q.pipRespond('otra pista');assert(said.join('\n').includes('Pista enfocada'),'Pip progressive scaffold: '+said);
said=[];q.pipRespond('dame la solución completa');assert(said.join('\n').includes('estructura segura')&&said.join('\n').includes('No voy a reemplazar'),'Pip refuses copy-ready answer: '+said);
said=[];q.pipRespond('dame una devolución como profesor');assert(said.join('\n').includes('Devolución de Pip')&&said.join('\n').includes('Criterios visibles'),'Pip teacher review: '+said);
q.setEditorCode('vida = 10\nvida = vida - 3\nprint(vida)');said=[];q.pipRespond('qué salida da mi código');assert(said.join('\n').includes('produce')&&said.join('\n').includes('7'),'Pip trace: '+said);
said=[];q.pipRespond('explicame la linea 2');assert(said.join('\n').includes('Línea 2')&&said.join('\n').includes('asigna'),'Pip specific line explanation: '+said);
q.setEditorCode('x = 4\nprint(x)');said=[];q.pipRespond('mejora mi código');assert(said.join('\n').includes('Revisión de claridad'),'Pip code quality: '+said);
said=[];q.pipRespond('¿por qué no puedo usar ñ en una variable?');assert(said.join('\n').includes('dano')&&said.join('\n').includes('textos'),'Pip identifier compatibility: '+said);
said=[];q.pipRespond('¿dónde está el manual?');assert(said.join('\n').includes('barra superior'),'Pip manual: '+said);
assert(q.badNames('daño = 12')&&!q.badNames('dano = 12\nprint("daño")'),'identifier detection');
const all=q.all(),ids=all.map(c=>c.id);assert.equal(new Set(ids).size,ids.length,'duplicate challenge IDs');assert.equal(all.filter(c=>c.interaction==='order').length,5);assert.equal(all.filter(c=>c.interaction==='choice').length,12);
for(const kind of ['Encontrar y corregir un error','Elegir un caso de prueba','Explicar un fragmento','Comparar soluciones','Depurar código','Completar una tabla de seguimiento','Mejorar nombres','Elegir una prueba límite','Simplificar código repetido'])assert(all.some(c=>c.activityKind===kind),kind);
assert.equal(all.find(c=>c.id==='op-4').starter,'dano = 4 + 3 * 2\nprint(dano)','ASCII-safe starter');
for(const c of all.filter(c=>c.interaction==='order')){assert(Array.isArray(c.blocks)&&c.blocks.length>=3,c.id+' blocks');for(const ck of c.checks)assert.equal(ck.test(c.blocks.join('\n')),true,c.id+' solution fails '+ck.label);}
for(const c of all.filter(c=>c.interaction==='choice'))assert(c.correct>=0&&c.correct<c.choices.length,c.id+' correct choice');
q.setScope('bonus-fizz');assert.equal(q.scope().length,1);assert.equal(q.scope()[0].id,'bonus-fizz');q.setScope(null);
q.state.agent='Luna';q.state.completed={};q.state.xpParcial={};q.state.inventory=[];q.topics[0].challenges.forEach(c=>q.state.completed[c.id]=true);const seal=q.genSeal(),parsed=q.parseSeal(seal);assert(parsed.ok&&parsed.partial&&((parsed.challengeBits[0]&1)||q.topics[0].challenges.every(c=>q.state.completed[c.id])),'seal roundtrip including partial topics');assert(!q.parseSeal(seal.slice(0,-1)+'Z').ok,'seal checksum');q.state.completed={};q.state.xpParcial={};q.applySeal(parsed.mask,'Luna');assert(q.topics[0].challenges.every(c=>q.state.completed[c.id]),'seal restore');
const sim=q.simulate('nombre = "Luna"\nprint("Hola", nombre)',[]);assert(sim&&sim.ok&&/Hola Luna/.test(sim.out),'basic local simulator');
q.state.agent='María José Núñez - estudiante de demostración';q.state.clase='Explorador';q.state.inventory=['Mapa de la taberna','Llave del conocimiento'];q.state.completed={};q.state.xpParcial={};q.state.xpPenalties=[];q.state.mastery={};q.state.learningLog=[];q.state.reflections={latest:'Aprendí a probar antes de ejecutar.'};
q.topics.slice(0,8).forEach(t=>t.challenges.forEach(c=>{q.state.completed[c.id]=true;q.state.xpParcial[c.id]=c.xp;}));
const formative=q.all()[1];q.state.maxChecks[formative.id]=1;q.state.xpParcial[formative.id]=12;q.state.xpPenalties=[{id:formative.id,lost:20}];q.recordXpPenalty(formative,formative.xp,4,3,false);assert(q.xpLostTotal()===0&&!q.state.xpPenalties.some(p=>p.id===formative.id),'legacy XP penalty removed');assert(q.xpTotal()>12,'completed mission grants full configured XP');
let pdfDemo='';context.FichaPDF.prototype.save=function(){pdfDemo=this.output();fs.writeFileSync(qaDir+'ficha-demostracion.pdf',pdfDemo,'ascii');};
q.exportPDF();
assert(/\/BaseFont \/Times-Bold/.test(pdfDemo)&&/\/Count 1\b/.test(pdfDemo)&&(/\/Subtype \/Image/g.exec(pdfDemo)||[]).length,'themed one-page PDF with logo');
assert((pdfDemo.match(/\/Subtype \/Image/g)||[]).length>=2,'PDF includes logo/hero and QR images');
assert(pdfDemo.includes('EVIDENCIA FORMATIVA')&&pdfDemo.includes('PUNTOS PERDIDOS: 0'),'PDF explains non-punitive progress');
assert(pdfDemo.includes('LEGENDARIO'),'PDF uses evolved hero stage');
assert(/\/Author \(Braian Mosqueira\)/.test(pdfDemo)&&(pdfDemo.match(/Braian Mosqueira/g)||[]).length===1,'author only in PDF metadata');
q.state.agent='Nombre muy largo '.repeat(20);q.all().forEach(c=>q.state.completed[c.id]=true);
context.FichaPDF.prototype.save=function(){fs.writeFileSync(qaDir+'ficha-extensa.pdf',this.output(),'ascii');};q.exportPDF();
console.log('PASS: syntax, '+(cases.length+12)+' Pip cases, 1366x768 and responsive mobile/iframe UI, multi-theme campaign routing, strong default guidance, non-punitive mastery, event-state hero CSS, automatic save and PDF recovery, local runtime, offline cache, themed one-page PDF, varied interactions, unique IDs, seal restore, local simulator, FizzBuzz scope, two actual PDF exports; '+q.all().length+' challenges retained.');
